package STH;

import java.sql.*;
import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gavito
 */
public class TotalRandom extends javax.swing.JPanel {

    private ArrayList<Restaurante> restaurantes;
    private int i = 0;
    private double prob = 100.0;
    private int minVisitas = 0;
    private Connection conect;
    
    public Restaurante restauranteElegido;
    
    public TotalRandom() throws SQLException, ClassNotFoundException {
        initComponents();
        restaurantes = new ArrayList<>();
        conect = Conexion.conectar();
        buscarRestaurantes(conect);
        asignarProbabilidades();
        
        Thread hilo = new Thread(new Randomizer());
        hilo.start();
    }
    
    public final void buscarRestaurantes(Connection conexion) throws SQLException{
        try{
            PreparedStatement query = conexion.prepareStatement("SELECT * FROM restaurantes ORDER BY Visitas DESC");
            ResultSet registros = query.executeQuery();
            while(registros.next()){
                restaurantes.add(new Restaurante());
                restaurantes.get(i).id = registros.getInt("ID_Restaurante");
                restaurantes.get(i).nombre = registros.getString("Restaurante");
                restaurantes.get(i).nivelDePrecios = registros.getString("Nivel_Precios");
                restaurantes.get(i).visitas = registros.getInt("Visitas");
                restaurantes.get(i).kmDistancia = registros.getFloat("Distancia_Km");
                restaurantes.get(i).tipo = registros.getString("Tipo");
                restaurantes.get(i).maximoPersonas = registros.getInt("Maximo_Personas");
                restaurantes.get(i).tiempoEstimado = registros.getFloat("Rapidez_Horas");
                
                if(restaurantes.get(i).visitas>minVisitas){
                    minVisitas = restaurantes.get(i).visitas;
                }
                i++;
            }
            i = 0;
        }
        catch(SQLException ex){
            throw new SQLException(ex);
        }
    }
    
    public final void asignarProbabilidades(){
        prob = 100;
        for(int j=0;j<restaurantes.size();j++){
            restaurantes.get(j).probabilidad = (prob/(restaurantes.size()-j)) - (2.5*(restaurantes.get(j).visitas-minVisitas));
            prob -= restaurantes.get(j).probabilidad;
        }
    }
        
    public void aumentarVisitasRestaurante(Connection conexion, Restaurante rest) throws SQLException{
        try{
            PreparedStatement query = conexion.prepareStatement("UPDATE restaurantes SET Visitas=? WHERE ID_Restaurante=?");
            query.setInt(1, rest.visitas+1);
            query.setInt(2, rest.id);
            query.executeUpdate();
        }catch(SQLException ex){
            throw new SQLException(ex);
        }
    }
    
    public Restaurante elegirRestaurante(){
        i = 0;
        prob = ThreadLocalRandom.current().nextDouble(0, 100);
        while(prob>0){
            prob-=restaurantes.get(i).probabilidad;
            i++;
        }
        return restaurantes.get(i-1);
    }

    class Randomizer implements Runnable{
        
        int i=0;
        int sleep;

        @Override
        public void run() {
            for(i = ThreadLocalRandom.current().nextInt(50, 100);i>0;i--){
                if(i>50){
                    sleep = 50;
                }else if(i>30){
                    sleep = 100;
                }else if(i>15){
                    sleep = 150;
                }else if(i>5){
                    sleep = 200;
                }else{
                    sleep = 250;
                }
                
                try {
                    Thread.sleep(sleep);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TotalRandom.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                restauranteElegido = elegirRestaurante();
                txtRest.setText(restauranteElegido.nombre);
            }
            lab1.setEnabled(true);
            lab2.setEnabled(true);
            jButton2.setEnabled(true);
        }

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtRest = new javax.swing.JTextField();
        lab2 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hoy comerás...");

        jButton1.setBackground(new java.awt.Color(163, 16, 16));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html>Volver a <div>empezar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(163, 16, 16));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<html>¡Está<div>bien!");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setEnabled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtRest.setEditable(false);
        txtRest.setBackground(new java.awt.Color(255, 255, 255));
        txtRest.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtRest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRest.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lab2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lab2.setForeground(new java.awt.Color(163, 16, 16));
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab2.setText("!");
        lab2.setEnabled(false);

        lab1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lab1.setForeground(new java.awt.Color(163, 16, 16));
        lab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab1.setText("!");
        lab1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRest, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRest)
                        .addComponent(lab1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.ventana.cambiarVentana(new Inicio());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            this.aumentarVisitasRestaurante(conect, restauranteElegido);
        } catch (SQLException ex) {
            Logger.getLogger(TotalRandom.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conect.close();
        } catch (SQLException ex) {
            Logger.getLogger(TotalRandom.class.getName()).log(Level.SEVERE, null, ex);
        }
        Main.ventana.cambiarVentana(new Inicio());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JTextField txtRest;
    // End of variables declaration//GEN-END:variables
}
